### ISSUE TITLE
Users with long usernames

### ISSUE THREAD

**Issue by Onurrr** [lorien/joinhider_bot#1]
When a user joins a group that has a very long username, the bot doesnt delete the joined message. example:
 
```
╋VX,QQ（同号）：253239090 专业工作室推广拉人【电报群拉国内外有无username都可拉、指定群拉人】【机器人定制】【社群代运营】【twitter关注、转发】【facebook关注、转发】【youtube点赞、评论】【出售成品电报账号】 （欢迎社群运营者、项目方、交易所洽谈合作）优质空投分享QQ群473157472 本工作室全网最低价、服务最好、活人质量最高 招收代理 We can ADD 1000+ 10000+ or ANY NUMBER REAL and ACTIVE MEMBERS for your TELEGRAM GROUPS-LEAVE NO JOIN ALERTS,QUALITY and QUANTITY GUARANTEED,DEMO AVAILABLE.We also provide READY-MADE TELEGRAM ACCOUNTS and BROADCASTING SERVICE now you read.(To get our sevic (@StanfordSwinburne)
```

![image](https://user-images.githubusercontent.com/9193729/43138422-17913fd6-8f4f-11e8-95d5-08933d8f2bb9.png)

**Comment by dignityinside** [comment]
+1

**Comment by lorien** [comment]
I can not reproduce this bug. I've set this exact name `╋VX,QQ（同号）：253239090 专业工作室推广拉人【电报群拉国内外有无username都可拉、指定群拉人】【机器人定制】【社群代运营】【twitter关注、转发】【facebook关注、转发】【youtube点赞、评论】【出售成品电报账号】 （欢迎社群运营者、项目方、交易所洽谈合作）优质空投分享QQ群473157472 本工作室全网最低价、服务最好、活人质量最高 招收代理 We can ADD 1000+ 10000+ or ANY NUMBER REAL and ACTIVE MEMBERS for your TELEGRAM GROUPS-LEAVE NO JOIN ALERTS,QUALITY and QUANTITY GUARANTEED,DEMO AVAILABLE.We also provide READY-MADE TELEGRAM ACCOUNTS and BROADCASTING SERVICE now you read.(To get our sevic (@StanfordSwinburne)` to first name of test account, then I use this account to join chat where joinhider_bot is already working. The bot deletes join message.
